"""
objective.py

Coordination objective + fault-type-aware setting-group logic.

Architecture (matches the paper)
--------------------------------
1. Predicted fault TYPE selects a setting-group scenario: a per-relay (zone)
   fault-current vector plus the minimum current that group's relays must
   still detect. Different types -> different levels -> different settings.
2. Model CONFIDENCE is a trust gate. >= CONFIDENCE_THRESHOLD -> use the
   predicted type's group; below it -> a conservative FALLBACK group that
   must detect the weakest fault of ANY type (uncertainty -> MORE conservative).
3. The objective is pure protection physics (no classifier call inside):
   small total-time term + graded penalties for CTI, pickup-window, and
   bound violations. CTI is checked per primary/backup pair at the SHARED
   downstream current (the corrected definition, lives in constraints.py).

TYPE_REF_CURRENT is now sourced from type_reference_currents.py's per-relay
path currents (real short-circuit/loaded-flow duty at each relay's own branch,
min-generation case) rather than a single characteristic value expanded by
the old ZONE_ATTENUATION**k radial model -- see the constant's own comment
block below for how to regenerate it. zone_currents_for_scenario still
supports a plain scalar too (via _expand_profile), for external callers that
override these constants with the old single-value shape.
"""

from relay_model import Relay
from constraints import (
    NUM_RELAYS, cti_shortfall, bounds_violation,
    W_CTI, W_BOUNDS, W_TIME,
)

relay = Relay()

CONFIDENCE_THRESHOLD = 0.70
ZONE_ATTENUATION = 0.85

# -------------------------------------------------------------------------
# COORDINATION REFERENCE CURRENTS (kA)
#
# SOURCE: these are the PER-RELAY lists generated by type_reference_currents.py's
# 5-relay-path extension (relay_path_bolted_currents / relay_path_overload_
# currents) for the MIN-GENERATION case -- real bolted (Zf=0) IEC 60909
# short-circuit duty (and, for OC, real loaded-flow current) read from each
# relay's OWN branch on the concrete path R1..R5 = buses 1-2-4-9-14-13, NOT
# a single characteristic value expanded by the old ZONE_ATTENUATION**k radial
# model, and NOT the noisy classifier dataset (which is deliberately
# noise-dominated for realistic classification and is the wrong source for a
# design calculation).
#
# Min-generation is used because it is the harder, more conservative
# coordination case (lowest available fault current -> relays must still be
# sensitive enough). Regenerate with `python type_reference_currents.py` and
# paste the case='min' per-relay lists here to refresh; the case='max' lists
# are the higher-duty alternative. Each TYPE_REF_CURRENT entry is already a
# [R1, R2, R3, R4, R5] kA list -- R4/R5 are voltage-referred back to the
# transmission base, and LLL/LL/SLG are already re-ranked per relay by
# type_reference_currents.py so every relay individually satisfies
# LLL > LL > SLG > OC (see _enforce_sc_ordering there for why that relabeling
# was needed). TYPE_MIN_CURRENT is derived, not pasted: the weakest
# (minimum) relay in that type's list -- the "minimum current the group's
# relays must still detect".
# -------------------------------------------------------------------------
TYPE_REF_CURRENT = {   # [R1, R2, R3, R4, R5] kA -- characteristic fault current per relay
    "LLL": [2.808, 1.482, 4.444, 0.410, 0.512],
    "LL":  [2.431, 1.178, 2.571, 0.355, 0.444],
    "SLG": [2.034, 1.020, 2.227, 0.231, 0.359],
    "OC":  [1.133, 0.408, 0.120, 0.073, 0.043],
}

# Derived (not pasted) so these never drift out of sync with the lists above.
TYPE_MIN_CURRENT = {label: min(currents) for label, currents in TYPE_REF_CURRENT.items()}

# Conservative worst-case PROFILE: at each relay position k, the lowest
# current across all 4 types -- "must detect the weakest fault of ANY type"
# (see module docstring). A list, like TYPE_REF_CURRENT's entries, so
# zone_currents_for_scenario's fallback branch returns a real per-relay
# profile instead of a single expanded scalar.
FALLBACK_REF_CURRENT = [
    min(TYPE_REF_CURRENT[label][k] for label in TYPE_REF_CURRENT)
    for k in range(NUM_RELAYS)
]
FALLBACK_MIN_CURRENT = min(TYPE_MIN_CURRENT.values())


def _expand_profile(value):
    """Normalize a reference-current entry to a NUM_RELAYS-length list.

    TYPE_REF_CURRENT/FALLBACK_REF_CURRENT are per-relay lists by default (see
    above). Some external callers (e.g. generalized_relay_pso.py's
    --generation switch) monkeypatch these to a single SCALAR characteristic
    current instead, for the old radial-attenuation model -- a scalar is
    expanded here with that same ZONE_ATTENUATION**k model so both shapes
    keep working without either caller needing to change.
    """
    if isinstance(value, (list, tuple)):
        return list(value)
    return [value * (ZONE_ATTENUATION ** k) for k in range(NUM_RELAYS)]


def zone_currents_for_scenario(fault_type, confidence):
    """Per-relay fault-current profile (kA) selected by the ML output.

    Confidence >= threshold -> the predicted type's characteristic profile.
    Below -> a conservative worst-case (lowest-current) profile, which is the
    hardest to coordinate and detect, i.e. uncertainty -> MORE conservative.
    """
    if confidence >= CONFIDENCE_THRESHOLD and fault_type in TYPE_REF_CURRENT:
        return _expand_profile(TYPE_REF_CURRENT[fault_type])
    return _expand_profile(FALLBACK_REF_CURRENT)


PICKUP_DETECT_MARGIN = 2.0 / 3.0
PICKUP_LOAD_MARGIN = 1.25
W_PICKUP = 1.0e2
# NOTE: with the per-relay TYPE_REF_CURRENT above, TYPE_MIN_CURRENT["OC"] is
# now R5's own weakest OC reading (0.043 kA, not the old single characteristic
# value of 0.377 kA), so the OC pickup ceiling (PICKUP_DETECT_MARGIN *
# TYPE_MIN_CURRENT["OC"] = 0.667 * 0.043 ~= 0.029 kA) now sits BELOW
# constraints.PICKUP_MIN (0.20 kA) -- the OC pickup window is infeasible again
# (same failure mode fixed once already, just re-triggered by the smaller OC
# figure this data source gives). Fixing it requires lowering PICKUP_MIN in
# constraints.py; not done here since this edit is scoped to objective.py only.


def select_scenario(fault_type, confidence):
    """Return (group_label, min_detect_current_kA) after the trust gate."""
    if confidence >= CONFIDENCE_THRESHOLD and fault_type in TYPE_MIN_CURRENT:
        return fault_type, TYPE_MIN_CURRENT[fault_type]
    return "FALLBACK", FALLBACK_MIN_CURRENT


def build_zone_currents(fault_current):
    """Per-relay fault current down the radial chain (kA)."""
    return [fault_current * (ZONE_ATTENUATION ** k) for k in range(NUM_RELAYS)]


def _pickup_window_penalty(position, zone_currents, min_detect, loading):
    pen = 0.0
    ceiling = PICKUP_DETECT_MARGIN * min_detect
    for k in range(NUM_RELAYS):
        pu = position[2 * k + 1]
        if pu > ceiling:
            pen += (pu - ceiling)
        load_floor = PICKUP_LOAD_MARGIN * loading * (ZONE_ATTENUATION ** k)
        if pu < load_floor:
            pen += (load_floor - pu)
        if pu >= zone_currents[k]:
            pen += (pu - zone_currents[k] + 1.0)
    return pen


def coordination_objective(position, zone_currents, min_detect, loading):
    total_time = 0.0
    for k in range(NUM_RELAYS):
        tds, pu = position[2 * k], position[2 * k + 1]
        i = zone_currents[k]
        total_time += 50.0 if pu >= i else relay.relay_operating_time(i, pu, tds)

    cti, _ = cti_shortfall(position, zone_currents)
    bnd = bounds_violation(position)
    pick = _pickup_window_penalty(position, zone_currents, min_detect, loading)
    return W_CTI * cti + W_BOUNDS * bnd + W_PICKUP * pick + W_TIME * total_time


def adaptive_objective(
    position, fault_current, loading, fault_type,
    fault_bus, fault_impedance, pre_fault_voltage, fault_voltage,
    confidence=1.0,
):
    """PSO entry point. Caller classifies ONCE and passes (fault_type,
    confidence) in; the objective never calls the model.

    INTERLINK: the predicted type (gated by confidence) selects BOTH the
    per-relay fault-current profile (zone_currents_for_scenario) AND the
    minimum-detectable current (select_scenario). The current profile drives
    every operating time, so the ML decision genuinely reshapes the
    optimization -- different types yield different coordinated settings.
    """
    _group, min_detect = select_scenario(fault_type, confidence)
    zone_currents = zone_currents_for_scenario(fault_type, confidence)
    return coordination_objective(position, zone_currents, min_detect, loading)